name: build

on:
  push:
    branches:
      - build-main
      - build-mturk
      - build-prolific

jobs:
  build-macos-executables:
    name: Build macOS app
    runs-on: macos-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              ref: ${{ github.ref }}
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: '3.12'
        - name: Install python dependencies
          run: |
              pip install -r requirements_macos.txt
              pip install --use-pep517 pynput@git+https://github.com/moses-palmer/pynput.git@25a43fddc5dab1ad8628fdf601760f1896af12f8
        - name: Download ffmpeg
          run: |
              cd agentnet-annotator/api/
              curl -L https://evermeet.cx/ffmpeg/ffmpeg-116720-g5c1c0325cd.zip -o ffmpeg.zip
              unzip ffmpeg.zip
              rm ffmpeg.zip
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '20.15.0'
        - name: Add macOS Certificates
          run: chmod +x add-osx-cert.sh && ./add-osx-cert.sh
          env:
              CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
              CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        - name: Build macOS Application
          env:
              APPLE_ID: ${{ secrets.APPLE_ID }}
              APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
              APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          run: |
              cd agentnet-annotator
              npm install
              npm run build-flask
              npm run make
              cd out/make
              mv agentnet-annotator-1.0.0-arm64.dmg ../../..
        - name: Upload dmg
          uses: actions/upload-artifact@v4
          with: 
            name: agentnet-annotator-1.0.0-arm64.dmg
            path: agentnet-annotator-1.0.0-arm64.dmg

  upload-to-gdrive:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: build-macos-executables
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: agentnet-annotator-1.0.0-arm64.dmg
          path: .
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "agentnet-annotator-1.0.0-arm64.dmg"
          name: "agentnet-annotator-1.0.0-arm64.dmg"
          folderId: ${{ secrets.MAIN_FOLDER_ID }}
          overwrite: "true"